server:
  port: 7200
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/log

# rocketmq相关配置
rocketmq:
  producer:
    group: LOG_PRODUCER

spring:
  application:
    # 配置服务名称
    name: logServer