server:
  port: 7600
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/file

# rocketmq相关配置
rocketmq:
  producer:
    group: FILE_PRODUCER

spring:
  application:
    # 配置服务名称
    name: fileServer