server:
  port: 8100
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/sms

# rocketmq相关配置
rocketmq:
  producer:
    group: SMS_PRODUCER

spring:
  application:
    # 配置服务名称
    name: smsServer