server:
  port: 8100
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/sms

# rocketmq相关配置
rocketmq:
  producer:
    group: SMS_PRODUCER

spring:
  application:
    # 配置服务名称
    name: smsServer
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    enabled: true
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    allow-request-override: false
    request-context-attribute: request
    suffix: .ftl