server:
  port: 7000
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/auth

# rocketmq相关配置
rocketmq:
  producer:
    group: AUTH_PRODUCER

spring:
  application:
    # 配置服务名称
    name: authServer
  #redis 连接地址配置
  redis:
    cluster:
      # 集群最大重连次数
      max-redirects: 3
      # 集群节点信息
      nodes:
        - 10.21.19.72:10001
        - 10.21.19.72:10002
        - 10.21.19.72:10003
        - 10.21.19.72:10004
        - 10.21.19.72:10005
        - 10.21.19.72:10006
    timeout: 60000
#    password: redispassxfkkslgoecjvkdlspdgje
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
