server:
  port: 7700
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/task

# rocketmq相关配置
rocketmq:
  producer:
    group: TASK_PRODUCER

spring:
  application:
    # 配置服务名称
    name: taskServer

