server:
  port: 7700
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/task

# rocketmq相关配置
rocketmq:
  producer:
    group: TASK_PRODUCER

spring:
  application:
    # 配置服务名称
    name: taskServer

# xxl-job配置
xxl:
  job:
    # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册机制，强烈建议配置此项，提升集群容错能力。
    app-name: ${ENV_NAME:doudoudrive-executor-job}
    # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
    log-path: ${ENV_PATH:logs/task/job}
    # 执行器日志文件保存天数 [选填] ：过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
    log-retention-days: ${ENV_DAYS:30}
    # 执行器通讯TOKEN [选填]：非空时启用，需要与调度中心配置的TOKEN一致
    accessToken: ${ENV_TOKEN:qhaejfn5gfz5nt1tq05zuff0ucq697fj}
    # 调度中心部署根地址 ，如调度中心集群部署存在多个地址则用逗号分隔。[选填]
    # 执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    adminAddresses: ${ENV_ADMIN_ADDRESSES:http://192.168.31.200:18000/xxl-job-admin}
    # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。
    # 从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
    address: ${ENV_ADDRESS:}
    # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP
    ip: ${ENV_IP:}
    # 执行器端口号 [选填]：小于等于0则自动获取，默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
    port: ${ENV_PORT:-1}