server:
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/common
      # 是否启动日志
      enabled: true
      # 日志格式
      pattern: common
      # 日志文件名前缀
      prefix: access_
      # 日志文件名后缀
      suffix: log
    # HTTP POST请求最大的大小
    max-http-post-size: 2048MB
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  # 优雅停机配置
  shutdown: graceful
spring:
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    view:
      suffix: .html
  lifecycle:
    # 设置缓冲期，最大等待时间
    timeout-per-shutdown-phase: 30s
  #配置 thymeleaf 模板
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  #redis 连接地址配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60000
    password: password
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: username
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      #设置单个上传文件的大小(单位字节)(4G)
      max-file-size: 4294967296
      #设置单次请求的文件上传的总大小(单位字节)(4G)
      max-request-size: 4294967296

# feign客户端超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: FULL

mybatis:
  mapperLocations: classpath*:com/doudoudrive/dao/*.xml
  type-aliases-package: com.doudoudrive.pojo
  configuration:
    mapUnderscoreToCamelCase: true

worker:
  tcp:
    url: http://192.168.31.200:1082/receive
    enable: true
  # 日志工蜂模块udp通信参数配置
  udp:
    # udp通信服务地址
    server: 192.168.31.200
    # udp通信端口
    port: 1082
    # 是否需要进行长度检查，如果为true，数据包将包含一个长度，以便在接收端进行检查
    lengthCheck: false
    # udp发送消息报文最大长度，udp 单个最大报文是 64kb(65536字节)，超过该长度需要采用tcp发送
    max-compress-bytes: 60000
    # 是否启用udp消息发送
    enable: true
