server:
  port: 80
  servlet:
    context-path: /
  undertow:
    accesslog:
      # Undertow 日志存放目录
      dir: logs/gateway

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    web-application-type: reactive
  application:
    # 配置服务名称
    name: gatewayServer
  cloud:
    # 网关配置
    gateway:
      routes:
        # 测试路由1 - www.baidu.com
        - id: bd_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,duniang
        # 测试路由2 - im.qq.com
        - id: qq_route
          uri: https://im.qq.com
          predicates:
            - Query=url,qq
        # 用户服务路由
        - id: user_route
          uri: lb://userInfoServer
          predicates:
            - Path=/userinfo/**
          filters:
            - RewritePath=/userinfo/(?<segment>.*),/userinfo/$\{segment}
        # 鉴权路由
        - id: auth_route
          uri: lb://authServer
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/oauth/(?<segment>.*),/oauth/$\{segment}
    # 阿里巴巴sentinel流量卫兵配置
    sentinel:
      eager: true
      transport:
        # 当前应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer，通过此端口收发数据
        port: ${ENV_SENTINEL_PORT:8719}
        # Sentinel控制台地址
        dashboard: 192.168.31.200:1080
      datasource:
        node1:
          nacos:
            # nacos服务器地址
            server-addr: http://192.168.31.200:8848
            dataId: ${spring.application.name}-sentinel.json
            groupId: DEV_GROUP
            data-type: json
            rule-type: flow
            # 命名空间
            namespace: ${spring.cloud.nacos.discovery.namespace}

#feign sentinel
feign:
  sentinel:
    enabled: on
